### ISSUE TITLE
Weird NDB failure

### ISSUE THREAD

**Issue by bcleenders** [bcleenders/hops#12]
```
17:34:37,970 DEBUG [main] (LightWeightRequestHandler.java:68)  INCREMENT_MIS_REPLICATED_FILES_INDEX - Transaction failed.
io.hops.exception.StorageException: com.mysql.clusterj.ClusterJDatastoreException: Error in NdbJTie: returnCode , code 4,009, mysqlCode 157, status 3, classification 11, message Cluster Failure .
    at io.hops.metadata.ndb.wrapper.HopsExceptionHelper.wrap(HopsExceptionHelper.java:34)
    at io.hops.metadata.ndb.wrapper.HopsSession.find(HopsSession.java:61)
    at io.hops.metadata.ndb.dalimpl.hdfs.VariableClusterj.getVariable(VariableClusterj.java:58)
    at io.hops.metadata.ndb.dalimpl.hdfs.VariableClusterj.getVariable(VariableClusterj.java:35)
    at io.hops.metadata.HdfsVariables$4.performTask(HdfsVariables.java:119)
    at io.hops.transaction.handler.LightWeightRequestHandler.execute(LightWeightRequestHandler.java:50)
    at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:52)
    at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:47)
    at io.hops.metadata.HdfsVariables.incrementMisReplicatedIndex(HdfsVariables.java:112)
    at io.hops.metadata.HdfsVariables.resetMisReplicatedIndex(HdfsVariables.java:107)
    at org.apache.hadoop.hdfs.MiniDFSCluster.deleteReplicasTable(MiniDFSCluster.java:2318)
    at org.apache.hadoop.hdfs.MiniDFSCluster.shutdown(MiniDFSCluster.java:1369)
    at org.apache.hadoop.hdfs.TestDFSRemove.testRemove(TestDFSRemove.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

```

**Comment by bcleenders** [comment]
seems like a connection issue -> closing
