### ISSUE TITLE
Transaction not begun in policy branch

### ISSUE THREAD

**Issue by bcleenders** [bcleenders/hops#16]
```
testGetFileStatusOnDir(org.apache.hadoop.hdfs.TestFileStatus)  Time elapsed: 2.877 sec  <<< ERROR!
org.apache.hadoop.ipc.RemoteException: Transaction is not begun.
    at io.hops.transaction.context.TransactionContext.aboutToPerform(TransactionContext.java:178)
    at io.hops.transaction.context.TransactionContext.find(TransactionContext.java:136)
    at io.hops.transaction.EntityManager.find(EntityManager.java:101)
    at org.apache.hadoop.hdfs.server.namenode.INode.getParent(INode.java:424)
    at org.apache.hadoop.hdfs.server.namenode.INode.getStoragePolicyID(INode.java:486)
    at org.apache.hadoop.hdfs.server.namenode.AbstractFileTree$1.performTask(AbstractFileTree.java:254)
    at io.hops.transaction.handler.LightWeightRequestHandler.execute(LightWeightRequestHandler.java:50)
    at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:52)
    at org.apache.hadoop.hdfs.server.namenode.AbstractFileTree.readSubtreeRoot(AbstractFileTree.java:231)
    at org.apache.hadoop.hdfs.server.namenode.AbstractFileTree.buildUp(AbstractFileTree.java:181)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.multiTransactionalGetContentSummary(FSNamesystem.java:6066)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getContentSummary(FSNamesystem.java:3111)
    at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getContentSummary(NameNodeRpcServer.java:766)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getContentSummary(ClientNamenodeProtocolServerSideTranslatorPB.java:769)
    at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java:65495)
```

**Comment by bcleenders** [comment]
Seems fixed in the bughunting branch.
