### ISSUE TITLE
Concurrent access IDsGenerator

### ISSUE THREAD

**Issue by bcleenders** [bcleenders/hops#4]
```
Exception in thread "IDsMonitor" Exception in thread "IDsMonitor" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
    at java.util.ArrayList$Itr.next(ArrayList.java:831)
    at io.hops.common.IDsGeneratorFactory.getNewIDs(IDsGeneratorFactory.java:98)
    at io.hops.common.IDsMonitor.getNewIds(IDsMonitor.java:82)
    at io.hops.common.IDsMonitor.run(IDsMonitor.java:75)
    at java.lang.Thread.run(Thread.java:745)
```

e.g. during TestNameNodeMetrics#testSyncAndBlockReportMetric (also with others)

**Comment by bcleenders** [comment]
Should be fixed in https://github.com/hopshadoop/hops/pull/260
